# Generated by Django 5.2.8 on 2025-11-11 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_blog_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='sub_title',
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category'),
        ),
    ]
